# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/mkd72/Desktop/calc1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(0, 1, 861, 111))
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.res_label = QtWidgets.QLabel(self.centralwidget)
        self.res_label.setGeometry(QtCore.QRect(0, 200, 861, 441))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.res_label.setFont(font)
        self.res_label.setText("")
        self.res_label.setObjectName("res_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 531, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_col_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_col_bt.setFont(font)
        self.add_col_bt.setObjectName("add_col_bt")
        self.horizontalLayout.addWidget(self.add_col_bt)
        self.del_col_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.del_col_bt.setFont(font)
        self.del_col_bt.setObjectName("del_col_bt")
        self.horizontalLayout.addWidget(self.del_col_bt)
        self.res_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.res_bt.setFont(font)
        self.res_bt.setObjectName("res_bt")
        self.horizontalLayout.addWidget(self.res_bt)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calc"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "X(значение)"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "P(вероятность)"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        self.add_col_bt.setText(_translate("MainWindow", "Добавить столбец"))
        self.del_col_bt.setText(_translate("MainWindow", "Удалить столбец"))
        self.res_bt.setText(_translate("MainWindow", "Рассчитать"))
